### ISSUE TITLE
Pro Tip: Making the Docker Container reachable from other machines

### ISSUE THREAD

**Issue by arbitercay** [Oliveriver/5d-diplomacy-with-multiverse-time-travel#22]
### For those interested in running this as a server for players to join without the client running locally

I was tinkering around with this for a while, I am not too familiar with docker so it took longer than I would like to admit. If you want to run this as a server for players to simply click a link and join, you'll need to edit the _docker-compose-yml_ file before running the container.

In the _ports_ section under the client configuration, change it from

```
services:
  frontend:
    build: client/
    ports:
      - 127.0.0.1:5173:8080
    restart: always
```

To

```
services:
  frontend:
    build: client/
    ports:
      - 5173:8080
    restart: always
```

Removing the localhost address (127.0.0.1) will make it so that other computers can connect to the game just by using a web browser.
Just putting this here for the next guy :)
